### PR TITLE
Support qutip>=5.0.0

### LINKED ISSUE #198: (Future) Compatibility with qutip 5.0.0
Even though qutip 5.0.0 hasn't been released yet, I accidentally found myself on qutip 5.0.0 for some project and therefore it became more convenient to use qutip 5.0.0 with scqubits. In this issue, I'm just sharing two compatibility fixes with qutip 5.0.0 that I found. I think that when qutip 5.0.0 is released, scqubits probably needs to be pinned to qutip<5.0.0, or scqubits can be made compatible with the _new_ qutip such that scqubit requires qutip>=5.0.0. 

## `inpt` argument of `qutip.Qobj` has been renamed to `arg`
There are 5 occurrences of the usage of `qutip.Qobj(inpt=...)` in scqubits, but this argument has been renamed to `arg` in version 5.0.0 of qutip. Changing to `qutip.Qobj(arg=...)` resolves all associated errors.  (Btw I think `arg` and `inpt` are both terrible names for this argument, I'd rather call it `data` or something but that's not up to us.) 

image

## qutip.Qobj(0)
One of the things that worked fine in previous version of qutip, but doesn't work anymore, is:

```
qutip.Qobj(0) + qutip.qeye(100)
```

Which now raises a `ValueError` because the `dims` of the objects are not the same. Hence, the solution is to set the `dims` argument to the appropriate value when setting `Qobj(0)`, for example: `qutip.Qobj(0, dims=[[100], [100]]) + qutip.qeye(100)` works fine in qutip 5.0.0. The only place where this is used in scqubits is in the HilbertSpace class. Here, we can use:

```
bare_hamiltonian = Qobj(0, dims=[[x.truncated_dim for x in self]]*len(self))
```

to circumvent this problem.

### PR DESCRIPTION
**Pull request by fedonman**
This PR provides support for the last major version of qutip.

Closes #198

### CODE REVIEW

**Comment by jkochNU** [comment]
@fedonman Thanks so much for contributing this pull request! I'm starting to look over it now (sorry for the delay). It looks like pytests are currently failing with 

``` 
>       dressed_op_data = id_wrapped_op.transform(dressed_evecs).data.to_array()
E       AttributeError: 'fast_csr_matrix' object has no attribute 'to_array'. Did you mean: 'toarray'?

scqubits/core/hilbert_space.py:1083: AttributeError
```

**Comment by fedonman** [comment]
> @fedonman Thanks so much for contributing this pull request! I'm starting to look over it now (sorry for the delay). It looks like pytests are currently failing with
> 
> ```
> >       dressed_op_data = id_wrapped_op.transform(dressed_evecs).data.to_array()
> E       AttributeError: 'fast_csr_matrix' object has no attribute 'to_array'. Did you mean: 'toarray'?
> 
> scqubits/core/hilbert_space.py:1083: AttributeError
> ```

Hello @jkochNU Thank you for the comment. I wanted to write a description of the progress so far, but totally forgot it. 

First of all, I corrected the error you mentioned, but since you got an error about not finding the `to_array` method, it means that you run the code with Qutip 4. I haven't changed the qutip version in requirements, since we don't want to force the update, but rather just support Qutip 5 for now. So you have to manually update the version in order to test that everything works there too. Or maybe create a new workflow?

Most of the changes needed to support Qutip 5 are about the breaking changes in the `Qobj` which are summarized [here](https://qutip.org/docs/pre-release/changelog.html#qobj-changes).

**Comment by jkochNU** [comment]
@fedonman Wonderful, and so glad about your help with this - thanks!

**Review by jkochNU — APPROVED** [review]
